version: 2.1

jobs:
  getcode:
    docker:
      - image: cimg/base:2023.08
    steps:
      - run:
          name: Get code
          shell: /bin/bash
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git config --global protocol.version 2
            git config --global http.maxConnections 10
            git clone --depth 1 --branch $CIRCLE_BRANCH  $CIRCLE_REPOSITORY_URL
            pwd
            ls
            rm -Rf .git
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    parameters:
      model:
        type: string
      sdk:
        type: string
      ui:
        type: string
    docker:
      - image: gnuton/asuswrt-merlin-toolchains-docker:latest
        environment:
          PROJECT_DIR: "/home/docker/project"
          CHANGELOG_FILE: "/tmp/CHANGELOG"
          MODEL: << parameters.model >>
          SDK: << parameters.sdk >>
          UI: << parameters.ui >>
          TERM: "xterm-256color"
    resource_class: large
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Set Version from TAG
          shell: /bin/bash
          command: |
            if [ -z "${CIRCLE_TAG}" ]; then
              echo "Nothing to do. Not a release."
            else
              MAJOR_VER=$(echo "${CIRCLE_TAG}" | sed -E 's/([0-9.]*)[_-]?(.*)/\1/')
              MINOR_VER=$(echo "${CIRCLE_TAG}" | sed -E 's/([0-9.]*)[_-]?(.*)/\2/')
              sed -i "s/SERIALNO=.*/SERIALNO=${MAJOR_VER}/g" release/src-rt/version.conf
              sed -i "s/EXTENDNO=.*/EXTENDNO=${MINOR_VER}/g" release/src-rt/version.conf
            fi
      - run:
          name: Generate changelog
          command: |
            python tools/get-last-notes.py > "${CHANGELOG_FILE}"
            cat "${CHANGELOG_FILE}"
      - run:
          name: Build firmware
          shell: /bin/bash
          no_output_timeout: 120m
          command: |
            export MERLINUPDATE=y
            cd ${PROJECT_DIR}/release/${SDK}
            echo "----- Files in dir: $(pwd) -----"
            ls -alh
            echo "----- Setting toolchains for ${SDK} -----"
            if [[ ${SDK} == "src-rt-5.04axhnd.675x" ]]; then
              source /home/docker/envs/bcm-hnd-ax-4.19.sh
            elif [[ ${SDK} == "src-rt-5.02axhnd.675x" ]]; then
              source /home/docker/envs/bcm-hnd.sh
            elif [[ ${SDK} == "src-rt-5.02axhnd" ]]; then
              source /home/docker/envs/bcm-hnd.sh
            else
              echo "SDK not supported"
              exit -1
            fi
            echo "----- Debugging env vars -----"
            env
            echo "------ Setting UI as $UI ---------"
            if [[ ${UI} == "tuf" ]]; then
              echo "Enabling TUF UI"
              sed -i 's/TUF_UI=n/TUF_UI=y/' ${PROJECT_DIR}/release/src-rt/target.mak
            fi
            echo "----- BUILD -----"
            (make ${MODEL} | tee "/tmp/build.log"; exit ${PIPESTATUS[0]})
            echo "------ DONE -----"
      - run:
          name: Prepare workspace
          shell: /bin/bash
          command: |
            mkdir -p workspace/release/
            export IMAGE_PATH=${PROJECT_DIR}/release/${SDK}/image/

            rm -rf ${IMAGE_PATH}/*cferom*
            for f in ${IMAGE_PATH}/*.w; do  md5sum "$f" > "$f.md5" ; done

            cp ${IMAGE_PATH}/*.md5 workspace/release
            cp ${IMAGE_PATH}/*ubi.w   workspace/release || :
            if [[ ${UI} == "none" ]]; then
              cp /tmp/build.log workspace/release/${MODEL}-build.log
            else
              cp /tmp/build.log workspace/release/${MODEL}_${UI}-build.log
            fi
            if [ -z "${CIRCLE_TAG}" ]; then
              echo "No CHANGELOG to copy. Not a release build."
            else
              # Changelogs are the same for each models since we are building from the same branch. We do use only the one generated by DSL-AX82U for now.
              if [[ ${MODEL} == "dsl-ax82u" ]]; then
                cp "${CHANGELOG_FILE}" workspace/release
              fi
            fi
      - store_artifacts:
          path: workspace/release      
      - persist_to_workspace:
          root: workspace
          paths:
            - release
  publish-manifest-and-notes:
    docker:
      - image: cibuilds/github:latest
    steps:
      - attach_workspace:
          at: workspace
      - add_ssh_keys:
          fingerprints:
            - "92:8c:58:f4:aa:44:98:aa:2f:ac:bc:8b:a5:de:f5:c2"
      - run:
          name: "Publish manifest and release note for the current build"
          command: |
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            
            git config --global user.email "bot@gnuton.org"
            git config --global user.name "Circle CI BOT"
            git config --global push.default simple
            git clone -b master --single-branch git@github.com:gnuton/asuswrt-merlin.ng.git
            
            cd asuswrt-merlin.ng
            UPDATE_DIR=updates
            MAJOR_VER=$(echo "${CIRCLE_TAG}" | sed -E 's/([0-9.]*)[_-]?(.*)/\1/')
            MINOR_VER=$(echo "${CIRCLE_TAG}" | sed -E 's/([0-9.]*)[_-]?(.*)/\2/')
            RELEASE_NOTE_FILE=$(echo "${MAJOR_VER}_${MINOR_VER}_note.txt" | sed "s/\./_/")
            echo "Generating manifest file..."
            echo "DSL-AC68U#FW${MAJOR_VER}#EXT${MINOR_VER}#BETAFW0#BETAEXT0#"       > ${UPDATE_DIR}/manifest.txt
            echo "DSL-AX82U#FW${MAJOR_VER}#EXT${MINOR_VER}#BETAFW0#BETAEXT0#"      >> ${UPDATE_DIR}/manifest.txt
            echo "RT-AX82U#FW${MAJOR_VER}#EXT${MINOR_VER}#BETAFW0#BETAEXT0#"       >> ${UPDATE_DIR}/manifest.txt
            echo "RT-AX82U_V2#FW${MAJOR_VER}#EXT${MINOR_VER}#BETAFW0#BETAEXT0#"    >> ${UPDATE_DIR}/manifest.txt
            echo "TUF-AX5400#FW${MAJOR_VER}#EXT${MINOR_VER}#BETAFW0#BETAEXT0#"     >> ${UPDATE_DIR}/manifest.txt
            echo "TUF-AX3000#FW${MAJOR_VER}#EXT${MINOR_VER}#BETAFW0#BETAEXT0#"     >> ${UPDATE_DIR}/manifest.txt
            echo "RT-AX95Q#FW${MAJOR_VER}#EXT${MINOR_VER}#BETAFW0#BETAEXT0#"       >> ${UPDATE_DIR}/manifest.txt
            echo "RT-AXE95Q#FW${MAJOR_VER}#EXT${MINOR_VER}#BETAFW0#BETAEXT0#"      >> ${UPDATE_DIR}/manifest.txt
            
            cp $HOME/project/workspace/release/CHANGELOG ${UPDATE_DIR}/"${RELEASE_NOTE_FILE}"
            echo "Uploading to github manifest and ${RELEASE_NOTE_FILE}"
            git add ${UPDATE_DIR}
            git commit -m "Updating Notes and manifest to version:${MAJOR_VER} ${MINOR_VER} [ci skip]" -a
            git push origin
  publish-github-release:
    docker:
      - image: cibuilds/github:latest
    steps:
      - attach_workspace:
          at: workspace
      - run: ls workspace/release
      - run:
          name: "Publish Release on Github"
          command: |
            echo "Uploading release..."
            RELEASE_TITLE="Stable: ${CIRCLE_TAG}"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete -n "${RELEASE_TITLE}" -b "$(cat workspace/release/CHANGELOG | head -n 50)" ${CIRCLE_TAG} workspace/release/
  publish-github-ci-pre-release:
    docker:
      - image: cibuilds/github:latest
    steps:
      - attach_workspace:
          at: workspace
      - run: ls workspace/release
      - run:
          name: "Publish CI pre-release on Github"
          command: |
            echo "Uploading CI pre-release..."
            RELEASE_TITLE="Unstable: ${CIRCLE_TAG}"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n "${RELEASE_TITLE}" -b "$(cat workspace/release/CHANGELOG | head -n 50)" -delete -prerelease ${CIRCLE_TAG} workspace/release/

workflows:
  version: 2.1
  build_and_release:
    jobs:
      - getcode:
          filters:
            tags:
              only: /.*/
      - build:
          name: "build_dsl-ax82u"
          model: "dsl-ax82u"
          ui: "none"
          sdk: "src-rt-5.02axhnd.675x"
          requires:
            - getcode
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - master
                - mainline
      - build:
          name: "build_rt-ax82u"
          model: "rt-ax82u"
          ui: "none"
          sdk: "src-rt-5.02axhnd.675x"
          requires:
            - getcode
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - master
                - mainline
      - build:
          name: "build_rt-ax82u_v2"
          model: "rt-ax82u_v2"
          ui: "none"
          sdk: "src-rt-5.04axhnd.675x"
          requires:
            - getcode
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - master
                - mainline
      - build:
          name: "build_rt-ax95q"
          model: "rt-ax95q"
          ui: "none"
          sdk: "src-rt-5.02axhnd.675x"
          requires:
            - getcode
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - master
                - mainline
      - build:
          name: "build_rt-axe95q"
          model: "rt-axe95q"
          ui: "none"
          sdk: "src-rt-5.02axhnd.675x"
          requires:
            - getcode
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - master
                - mainline
      - build:
          name: "build_tuf-ax5400"
          model: "tuf-ax5400"
          ui: "none"
          sdk: "src-rt-5.02axhnd.675x"
          requires:
            - getcode
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - master
                - mainline
      - build:
          name: "build_tuf-ax3000"
          model: "tuf-ax3000"
          ui: "none"
          sdk: "src-rt-5.02axhnd.675x"
          requires:
            - getcode
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - master
                - mainline
      - build:
          name: "build_tuf-ax5400_tuf"
          model: "tuf-ax5400"
          ui: "tuf"
          sdk: "src-rt-5.02axhnd.675x"
          requires:
            - getcode
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - master
                - mainline
      - build:
          name: "build_tuf-ax3000_tuf"
          model: "tuf-ax3000"
          ui: "tuf"
          sdk: "src-rt-5.02axhnd.675x"
          requires:
            - getcode
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - master
                - mainline
      - build:
          name: "build_rt-ax92u"
          model: "rt-ax92u"
          ui: "none"
          sdk: "src-rt-5.02axhnd"
          requires:
            - getcode
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - master
                - mainline
      - request-testing:
          type: approval
          filters:
            tags:
              only: /[0-9]+.*gnuton[0-9]+/
            branches:
              ignore: /.*/
          requires:
            - build_dsl-ax82u
            - build_rt-ax82u
            - build_tuf-ax5400
            - build_tuf-ax3000
            - build_tuf-ax5400_tuf
            - build_tuf-ax3000_tuf
            - build_rt-ax95q
            - build_rt-axe95q
            - build_rt-ax92u
            - build_rt-ax82u_v2
      - publish-manifest-and-notes:
          filters:
            tags:
              only: /[0-9]+.*gnuton[0-9]+/
            branches:
              ignore: /.*/
          requires:
            - request-testing
      - publish-github-release:
          filters:
            tags:
              only: /[0-9]+.*gnuton[0-9]+/
            branches:
              ignore: /.*/
          requires:
            - publish-manifest-and-notes
      - publish-github-ci-pre-release:
          filters:
            tags:
              only: 
               - /gnuton-snapshot-.*/
               - /[0-9]+.*gnuton[0-9]+_beta[0-9]+/
               - /[0-9]+.*gnuton[0-9]+_alpha[0-9]+/
            branches:
              ignore: /.*/
          requires:
            - build_dsl-ax82u
            - build_rt-ax82u
            - build_tuf-ax5400
            - build_tuf-ax3000
            - build_tuf-ax5400_tuf
            - build_tuf-ax3000_tuf
            - build_rt-ax95q
            - build_rt-axe95q
            - build_rt-ax92u
            - build_rt-ax82u_v2
notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/c26cd1f27c23a32898e9
